"""Render the profile package table with live GitHub and Pepy badges.

Edit GROUPS and CONCEPTS here when changing table order or descriptions. The
block between STATS_START/STATS_END in README.md is regenerated by this script.
No counts are fetched or committed; badge providers supply them when viewed.
"""
import argparse
import json
import re
from pathlib import Path

OWNER = "ArturSepp"
SCRIPT_DIR = Path(__file__).resolve().parent
README_PATH = SCRIPT_DIR.parent / "README.md"
REGISTRY = json.loads((SCRIPT_DIR / "public_registry.json").read_text(encoding="utf-8"))
DOCS = {p["dist"]: f"https://{p['rtd']}.readthedocs.io" for p in REGISTRY["packages"]}

REPOS = {
    "QuantInvestStrats": "qis",
    "OptimalPortfolios": "optimalportfolios",
    "factorlasso": "factorlasso",
    "StochVolModels": "stochvolmodels",
    "OptionChainAnalytics": "option-chain-analytics",
    "VanillaOptionPricers": "vanilla-option-pricers",
    "TrendFollowingSystems": "trendfollowing",
    "GoalBasedAllocation": "goal-based-allocation",
    "privateassets": "privateassets",
    "BloombergFetch": "bbg-fetch",
}

CONCEPTS = {
    "QuantInvestStrats": "Performance analytics, backtesting and factsheets",
    "OptimalPortfolios": "Portfolio optimisation and rolling backtests",
    "factorlasso": "Sparse factor models with sign-constrained LASSO",
    "StochVolModels": "Stochastic volatility pricing and calibration",
    "VanillaOptionPricers": "Vectorised BSM and Bachelier pricing",
    "OptionChainAnalytics": "Point-in-time option-chain data and queries",
    "TrendFollowingSystems": "Closed-form trend-following analytics",
    "GoalBasedAllocation": "Goal-based allocation with wealth floors",
    "privateassets": "Multi-factor PME for private assets",
    "BloombergFetch": "Bloomberg data in pandas DataFrames",
}

GROUPS = {
    "Portfolio Construction, Factor Models, Backtest Reporting":
        ["QuantInvestStrats", "OptimalPortfolios", "factorlasso"],
    "Volatility and Option Modelling":
        ["StochVolModels", "OptionChainAnalytics", "VanillaOptionPricers"],
    "Dynamic Trading Strategies":
        ["TrendFollowingSystems", "GoalBasedAllocation"],
    "Illiquid Private Markets":
        ["privateassets"],
    "Data":
        ["BloombergFetch"],
}

if [repo for repos in GROUPS.values() for repo in repos] != list(REPOS) or set(CONCEPTS) != set(REPOS):
    raise SystemExit("GROUPS, REPOS and CONCEPTS must list the same repositories, "
                     "with REPOS in the order GROUPS defines")


def row(repo: str, slug: str, concept: str) -> str:
    """Render one row; each metric is supplied at view time by its provider."""
    base = f"https://github.com/{OWNER}/{repo}"
    version = (f"[![](https://img.shields.io/pypi/v/{slug}?style=flat-square&label=&color=blue)]"
               f"(https://pypi.org/project/{slug}/)")
    stars = (f"[![Stars](https://img.shields.io/github/stars/{OWNER}/{repo}?style=flat-square&label=)]"
             f"({base}/stargazers)")
    forks = (f"[![Forks](https://img.shields.io/github/forks/{OWNER}/{repo}?style=flat-square&label=)]"
             f"({base}/network/members)")
    downloads_url = f"https://pepy.tech/project/{slug}"
    badge = f"https://static.pepy.tech/personalized-badge/{slug}"
    monthly = (f"[![Monthly downloads]({badge}?period=month&units=international_system&left_text=)]"
               f"({downloads_url})")
    total = (f"[![Total downloads]({badge}?period=total&units=international_system&left_text=)]"
             f"({downloads_url})")
    return (f"| [{repo}]({base}) ({slug}) · [Docs]({DOCS[slug]}) | {concept} | "
            f"{version} | {stars} | {forks} | {monthly} | {total} |")


def build_table() -> str:
    header = ("| Package | Concept | Version | Stars | Forks | Monthly<br>Downloads | Total<br>Downloads |\n"
              "|---------|---------|:-------:|:-----:|:-----:|:-----------------:|:---------------:|")
    body = []
    for group, repos in GROUPS.items():
        body.append(f"| **{group}** | | | | | | |")
        body.extend(row(repo, REPOS[repo], CONCEPTS[repo]) for repo in repos)
    return f"{header}\n" + "\n".join(body)


def replace_table(readme: str, table: str) -> str:
    new_readme, n = re.subn(
        r"<!-- STATS_START -->.*?<!-- STATS_END -->",
        lambda _: f"<!-- STATS_START -->\n{table}\n<!-- STATS_END -->",
        readme,
        flags=re.DOTALL,
    )
    if n != 1:
        raise SystemExit("Expected exactly one STATS_START/STATS_END marker pair in README.md")
    return new_readme


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed table needs regeneration")
    args = parser.parse_args()
    readme = README_PATH.read_text(encoding="utf-8")
    rendered = replace_table(readme, build_table())
    if args.check:
        if rendered != readme:
            raise SystemExit("Profile table is out of date; run python scripts/build_stats.py")
    elif rendered != readme:
        README_PATH.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
